//! ACP tool call adapter test (test_15)

use super::common::team_helpers::*;

/// E2E Test 15: A2A → ACP Tool Call Adapter Verification
///
/// Verifies that the a2a-acp-adapter correctly:
/// 1. Captures tool-call-update SSE events from gemini-cli
/// 2. Converts them to ACP tool_call JSON format
/// 3. Includes toolCalls in assistant_turn_patch UI events
/// 4. Persists tool_calls to the session DB
///
/// Run: cargo test test_15_a2a_acp_tool_call_e2e -- --nocapture
#[ignore]
#[tokio::test]
async fn test_a2a_acp_tool_call_e2e() {
    use a2a_rs::event::EventBus;
    use a2a_rs::executor::{AgentExecutor, RequestContext};
    use a2a_rs::types::*;
    use ilhae_proxy::a2a_persistence::ForwardingExecutor;

    println!("\n══════════════════════════════════════════════════════════");
    println!("🧪 test_15: A2A → ACP Tool Call Adapter E2E");
    println!("══════════════════════════════════════════════════════════\n");

    let dir = ilhae_dir();
    let team = load_team_runtime_config(&dir).expect("team.json required");
    let leader = team
        .agents
        .iter()
        .find(|a| a.role.to_lowercase().contains("leader"))
        .expect("Leader agent required");

    // ── Spawn agents ──
    let workspace_map = generate_peer_registration_files(&team, None);
    let mut children =
        spawn_team_a2a_servers(&team, &workspace_map, None, "e2e-tool-call-test").await;

    match wait_for_all_team_health(&team).await {
        Ok(()) => println!("✅ All agents healthy"),
        Err(e) => {
            cleanup_children(&mut children).await;
            panic!("Health check failed: {}", e);
        }
    }
    trigger_agent_reload(&team).await;
    println!("✅ Agents spawned and healthy");

    // ── Step 1: Create session ──
    let session_id = uuid::Uuid::new_v4().to_string();
    let mut store = SessionStore::new(&dir).expect("SessionStore");

    let brain_dir = dir.join("brain");
    let writer = brain_session_rs::brain_session_writer::BrainSessionWriter::new(&brain_dir);
    store.set_brain_writer(writer);
    let store = std::sync::Arc::new(store);

    store
        .ensure_session_with_channel(&session_id, "leader", ".", "team")
        .expect("ensure_session");
    store
        .update_session_title(&session_id, "🧪 A2A-ACP Tool Call E2E")
        .ok();
    println!("✅ Step 1: Session {} created", &session_id[..8]);

    // ── Step 2: Create ForwardingExecutor (with adapter) ──
    let cx_cache = ilhae_proxy::CxCache {
        inner: std::sync::Arc::new(tokio::sync::RwLock::new(Vec::new())),
    };
    let executor = ForwardingExecutor::with_main_flag(
        leader.endpoint.trim_end_matches('/').to_string(),
        "leader".to_string(),
        true,
        store.clone(),
        cx_cache,
    );

    let artifact_dir = executor.resolve_artifact_dir(&session_id);
    println!(
        "✅ Step 2: Executor created, artifact_dir: {:?}",
        artifact_dir
    );

    // ── Step 3: Send prompt that requires tool calls ──
    // Use a natural prompt that triggers tool usage (artifact_save, write_file, etc.)
    // The test purpose is to verify SSE tool-call events are captured, not which tool is used.
    let user_prompt = if let Some(ref adir) = artifact_dir {
        format!(
            "다음 디렉토리에 test_output.md 파일을 생성해줘: {}\n\
             파일 내용:\n```\n# Test Output\n\nGenerated by E2E test.\n```",
            adir.display()
        )
    } else {
        "현재 작업 디렉토리에 test_output.md 파일을 생성해줘.\n\
         파일 내용:\n```\n# Test Output\n\nGenerated by E2E test.\n```"
            .to_string()
    };

    // Persist user message
    let content_blocks = serde_json::to_string(&vec![
        serde_json::json!({"type": "text", "text": user_prompt}),
    ])
    .unwrap_or_else(|_| "[]".to_string());
    store
        .add_full_message_with_blocks(
            &session_id,
            "user",
            &user_prompt,
            "leader",
            "",
            "[]",
            &content_blocks,
            0,
            0,
            0,
            0,
        )
        .expect("persist user message");
    println!("✅ Step 3a: User message persisted");

    let request = SendMessageRequest {
        message: Message {
            message_id: uuid::Uuid::new_v4().to_string(),
            context_id: Some(session_id.clone()),
            task_id: None,
            role: Role::User,
            parts: vec![Part {
                kind: Some("text".to_string()),
                text: Some(user_prompt.clone()),
                raw: None,
                url: None,
                data: None,
                metadata: None,
                filename: None,
                media_type: None,
            }],
            metadata: None,
            extensions: vec![],
            reference_task_ids: None,
        },
        configuration: None,
        metadata: None,
    };

    let context = RequestContext {
        task_id: Some(uuid::Uuid::new_v4().to_string()),
        context_id: session_id.clone(),
        request,
    };

    let event_bus = EventBus::new(100);
    let mut event_rx = event_bus.subscribe();
    println!("  ⏳ Step 3b: Sending to real agent via ForwardingExecutor.execute()...");

    let result = tokio::time::timeout(
        Duration::from_secs(120),
        executor.execute(context, &event_bus),
    )
    .await;

    // ── Step 4: Collect SSE events and check for tool calls ──
    let mut accumulated_text = String::new();
    let mut tool_call_events: Vec<serde_json::Value> = Vec::new();

    match result {
        Ok(Ok(())) => {
            println!("✅ Step 3b: ForwardingExecutor.execute() completed");
        }
        Ok(Err(e)) => {
            println!("⚠️ Step 3b: execute() error: {}", e);
        }
        Err(_) => {
            println!("⚠️ Step 3b: execute() timed out after 120s");
        }
    }

    // Drain event bus
    loop {
        match tokio::time::timeout(Duration::from_millis(100), event_rx.recv()).await {
            Ok(Ok(event)) => {
                match &event {
                    a2a_rs::event::ExecutionEvent::StatusUpdate(su) => {
                        if let Some(msg) = &su.status.message {
                            let text = a2a_rs::proxy::extract_text_from_parts(&msg.parts);
                            if !text.is_empty() {
                                accumulated_text = text;
                            }
                        }
                        // Check for tool-call-update in metadata (new URI + legacy)
                        if let Some(meta) = &su.metadata {
                            let ext_key = a2a_acp_adapter::tool_call::TOOL_CALL_EXT_URI;
                            let ca = meta.get(ext_key).or_else(|| meta.get("coderAgent"));
                            if let Some(ca_val) = ca {
                                let kind =
                                    ca_val.get("kind").and_then(|v| v.as_str()).unwrap_or("");
                                if kind == "tool-call-update" {
                                    println!("  🔧 Tool call event: {:?}", ca_val);
                                    tool_call_events.push(ca_val.clone());
                                }
                            }
                        }
                    }
                    a2a_rs::event::ExecutionEvent::Task(task) => {
                        if let Some(msg) = &task.status.message {
                            let text = a2a_rs::proxy::extract_text_from_parts(&msg.parts);
                            if !text.is_empty() {
                                accumulated_text = text;
                            }
                        }
                    }
                    _ => {}
                }
            }
            _ => break,
        }
    }

    // ── Step 5: Verify tool calls were captured ──
    println!("\n── Tool Call Verification ──");
    println!(
        "  Total tool-call-update events: {}",
        tool_call_events.len()
    );
    for (i, tc) in tool_call_events.iter().enumerate() {
        let name = tc.get("toolName").and_then(|v| v.as_str()).unwrap_or("?");
        let status = tc.get("status").and_then(|v| v.as_str()).unwrap_or("?");
        let id = tc.get("toolCallId").and_then(|v| v.as_str()).unwrap_or("?");
        let response_text = tc
            .get("responseText")
            .and_then(|v| v.as_str())
            .unwrap_or("?");
        println!(
            "  [{}] tool={} status={} id={} responseText={}",
            i, name, status, id, response_text
        );
    }

    // ── Step 6: Check DB persistence ──
    println!("\n── DB Persistence Verification ──");
    let messages = store.load_session_messages(&session_id).unwrap_or_default();
    println!("  Total messages in DB: {}", messages.len());

    let mut found_tool_calls_in_db = false;
    for msg in &messages {
        let content_preview: String = msg.content.chars().take(80).collect();

        println!(
            "  📝 role={} agent={} tool_calls_len={} content={}...",
            msg.role,
            msg.agent_id,
            msg.tool_calls.len(),
            content_preview
        );

        if msg.role == "assistant" && msg.tool_calls.len() > 2 {
            found_tool_calls_in_db = true;
            // Parse and display tool calls
            if let Ok(tcs) = serde_json::from_str::<Vec<serde_json::Value>>(&msg.tool_calls) {
                println!("  ✅ Found {} tool calls in DB:", tcs.len());
                for tc in &tcs {
                    let name = tc.get("name").and_then(|v| v.as_str()).unwrap_or("?");
                    let status = tc.get("status").and_then(|v| v.as_str()).unwrap_or("?");
                    let source = tc.get("source").and_then(|v| v.as_str()).unwrap_or("?");
                    println!("    🔧 name={} status={} source={}", name, status, source);
                }
            }
        }
    }

    // ── Step 7: Also test the adapter directly ──
    println!("\n── A2A-ACP Adapter Unit Verification ──");
    let test_meta = serde_json::json!({
        "urn:google:a2a:ext:tool-call-reporting": {
            "kind": "tool-call-update",
            "toolName": "write_to_file",
            "status": "completed",
            "toolCallId": "e2e-test-001"
        }
    });
    let acp_tc = a2a_acp_adapter::a2a_metadata_to_acp_tool_call(&test_meta);
    assert!(
        acp_tc.is_some(),
        "Adapter should convert extension URI metadata"
    );
    let acp_tc = acp_tc.unwrap();
    assert_eq!(acp_tc["name"], "write_to_file");
    assert_eq!(acp_tc["status"], "completed");
    assert_eq!(acp_tc["source"], "a2a");
    println!("  ✅ Adapter correctly converts extension URI metadata → ACP format");

    // Also test legacy coderAgent key
    let legacy_meta = serde_json::json!({
        "coderAgent": {
            "kind": "tool-call-update",
            "toolName": "run_command",
            "status": "started",
            "toolCallId": "legacy-001"
        }
    });
    let legacy_tc = a2a_acp_adapter::a2a_metadata_to_acp_tool_call(&legacy_meta);
    assert!(
        legacy_tc.is_some(),
        "Adapter should also handle legacy coderAgent key"
    );
    println!("  ✅ Adapter also handles legacy coderAgent key (backward compat)");

    cleanup_children(&mut children).await;

    println!("\n══════════════════════════════════════════════════════════");
    println!("✅ test_15 A2A → ACP Tool Call Adapter E2E Complete");
    println!("  Session: {}", &session_id[..8]);
    println!(
        "  Tool call SSE events captured: {}",
        tool_call_events.len()
    );
    println!("  Tool calls persisted in DB: {}", found_tool_calls_in_db);
    println!("  Accumulated text: {}B", accumulated_text.len());
    println!("══════════════════════════════════════════════════════════");

    // Soft assertions (don't fail — LLM behavior is non-deterministic)
    if tool_call_events.is_empty() {
        println!("⚠️ Note: No tool-call-update events captured. Agent might not have used tools.");
    }
    if !found_tool_calls_in_db {
        println!("⚠️ Note: No tool_calls found in DB. Main agent uses SSE for UI streaming.");
    }
}
