// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuQueueLeaseMode } from "./GpuQueueLeaseMode";
import type { GpuQueueLeaseState } from "./GpuQueueLeaseState";

export type GpuQueueLeaseSnapshot = { leaseId: string, owner: string, kind: string, mode: GpuQueueLeaseMode, state: GpuQueueLeaseState, preemptLlm: boolean, llmWasPreempted: boolean, queuedAt: bigint, grantedAt: bigint | null, expiresAt: bigint | null, };
