// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuQueueLeaseSnapshot } from "./GpuQueueLeaseSnapshot";
import type { GpuQueueLlmRuntimeState } from "./GpuQueueLlmRuntimeState";
import type { GpuQueueRuntimeEventType } from "./GpuQueueRuntimeEventType";

export type GpuQueueRuntimeEventNotification = { eventId: string, createdAt: bigint, eventType: GpuQueueRuntimeEventType, message: string, llmState: GpuQueueLlmRuntimeState, lease: GpuQueueLeaseSnapshot | null, };
