// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopLifecycleItem } from "../LoopLifecycleItem";
import type { LoopLifecycleKind } from "../LoopLifecycleKind";

export type IlhaeLoopLifecycleNotification = { "event": "started", sessionId: string, item: LoopLifecycleItem, } | { "event": "progress", sessionId: string, itemId: string, kind: LoopLifecycleKind, summary: string, detail?: string, counts?: { [key in string]?: bigint }, } | { "event": "completed", sessionId: string, item: LoopLifecycleItem, } | { "event": "failed", sessionId: string, item: LoopLifecycleItem, };
