// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopLifecycleKind } from "../LoopLifecycleKind";

export type LoopLifecycleProgressNotification = { threadId: string, turnId: string, itemId: string, kind: LoopLifecycleKind, summary: string, detail?: string, counts?: { [key in string]?: bigint }, };
