// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type McpCompletionCompleteParams = { threadId?: string | null, server: string, ref: JsonValue, argument: JsonValue, context?: JsonValue, };
