// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalLoopHistoryEntry } from "./ThreadGoalLoopHistoryEntry";
import type { ThreadGoalLoopState } from "./ThreadGoalLoopState";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoal = { threadId: string, objective: string, status: ThreadGoalStatus, tokenBudget: number | null, tokensUsed: number, timeUsedSeconds: number, createdAt: number, updatedAt: number, loopState: ThreadGoalLoopState | null, loopHistory: Array<ThreadGoalLoopHistoryEntry>, };
