// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalLoopPhase } from "./ThreadGoalLoopPhase";
import type { ThreadGoalLoopStatus } from "./ThreadGoalLoopStatus";

export type ThreadGoalLoopState = { cycleNumber: number, phase: ThreadGoalLoopPhase, status: ThreadGoalLoopStatus, summary: string, updatedAt: number, };
