// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalLoopPhase } from "./ThreadGoalLoopPhase";
import type { ThreadGoalLoopStatus } from "./ThreadGoalLoopStatus";

export type ThreadGoalLoopHistoryEntry = { id: string, cycleNumber: number, phase: ThreadGoalLoopPhase, status: ThreadGoalLoopStatus, title: string, summary: string, detail: string | null, error: string | null, startedAt: number, updatedAt: number, completedAt: number | null, };
