// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopLifecycleKind } from "./LoopLifecycleKind";
import type { LoopLifecycleStatus } from "./LoopLifecycleStatus";

export type LoopLifecycleItem = { id: string, kind: LoopLifecycleKind, title: string, summary: string, detail?: string, status: LoopLifecycleStatus, reason?: string, counts?: { [key in string]?: bigint }, error?: string, duration_ms?: bigint, target_profile?: string, };
