// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoopLifecycleKind = "context_injection" | "execution_loop" | "verification_loop" | "advisor" | "super_loop" | "improvement_loop";
