// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parameter accepted by an MCP prompt template.
 */
export type PromptArgument = { name: string, title?: string, description?: string, required?: boolean, };
