// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptArgument } from "./PromptArgument";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A prompt template exposed by an MCP server.
 */
export type Prompt = { name: string, title?: string, description?: string, arguments?: Array<PromptArgument>, icons?: Array<JsonValue>, _meta?: JsonValue, };
