// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchContextSize } from "./WebSearchContextSize";
import type { WebSearchEngine } from "./WebSearchEngine";
import type { WebSearchLocation } from "./WebSearchLocation";

export type WebSearchToolConfig = { context_size: WebSearchContextSize | null, allowed_domains: Array<string> | null, location: WebSearchLocation | null, searxng_url: string | null, use_duckduckgo_fallback: boolean | null, engine: WebSearchEngine | null, };
