use std::sync::Arc;

use agent_client_protocol_schema::{ContentBlock, TextContent};
use brain_rs::BrainService;
use brain_session_rs::session_store::SessionInfo;
use moka::sync::Cache;
use tokio::sync::RwLock;
use tracing::info;

use crate::{
    ARTIFACT_INSTRUCTION, infer_agent_id_from_command,
    session_persistence_service::SessionRegistryService, settings_store::SettingsStore,
};

const ADVISOR_MODE_REVIEW_FIRST_INSTRUCTION: &str = r#"
<system_directive priority="high">
ADVISOR MODE IS ENABLED.
- Treat this as a response contract for every turn, not just an initial preference.
- Default to analysis, review, risk discovery, and plan-first guidance.
- Do not rush into mutating actions unless the user explicitly asks for execution.
- Prefer surfacing trade-offs, assumptions, unknowns, and safer alternatives before acting.
- When the user has not explicitly asked for execution, prefer a concise structure:
  1. current understanding
  2. key risks or gaps
  3. recommended approach
  4. concrete next steps
- When execution is requested, keep the advisory framing concise, then proceed with the requested work.
- If a requested action looks high-risk, say why before executing.
</system_directive>
"#;

const ADVISOR_MODE_RISK_FIRST_INSTRUCTION: &str = r#"
<system_directive priority="high">
ADVISOR MODE IS ENABLED.
- Treat this as a response contract for every turn, not just an initial preference.
- Lead with risk discovery, failure modes, missing evidence, and safer alternatives before proposing execution.
- When the user has not explicitly asked for execution, prefer a concise structure:
  1. key risks first
  2. why they matter
  3. safest viable approach
  4. next step if the user wants execution
- If execution is requested, still call out the main risk boundary before acting.
</system_directive>
"#;

const ADVISOR_MODE_PLAN_FIRST_INSTRUCTION: &str = r#"
<system_directive priority="high">
ADVISOR MODE IS ENABLED.
- Treat this as a response contract for every turn, not just an initial preference.
- Default to planning and decomposition before execution.
- When the user has not explicitly asked for execution, prefer a concise structure:
  1. current understanding
  2. recommended plan
  3. dependencies or gaps
  4. next executable step
- If execution is requested, give the shortest viable plan framing, then proceed.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_REVIEW_ONLY_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Preset: review_only.
- Do not auto-apply memory changes.
- Prefer identifying reusable knowledge, surfacing candidates, and asking for review before promotion or extraction.
- Use dream analysis to decide what should be reviewed, summarized, promoted, or ignored.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_SAFE_SUMMARIZE_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Preset: safe_summarize.
- Prefer capturing durable knowledge when the interaction yields reusable facts, preferences, or stable procedures.
- Use dream analysis deliberately and allow safe summarization of clearly repetitive memory groups.
- Do not auto-promote or auto-extract unless the action is explicitly requested.
- Keep the working conversation concise and externalize reusable learnings into the brain layer when justified.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_SAFE_APPLY_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Preset: safe_apply.
- Prefer converting clearly reusable, stable outputs into durable memory artifacts.
- Safe summarization of repetitive dream groups is allowed.
- When a promotion or extraction target is explicit and low-risk, prefer applying it instead of leaving only a suggestion.
- If the target or effect is ambiguous, fall back to review-first behavior instead of forcing an apply.
- Keep the working conversation concise and externalize reusable learnings into the brain layer when justified.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_GEPA_SIDECAR_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Preset: gepa_sidecar.
- Keep self-improvement actions review-first unless the target is explicitly low-risk.
- Super-loop follow-up text may be optimized by an external DSPy/GEPA sidecar before task creation.
- Prefer producing auditable summaries, clear next actions, and conservative apply decisions over aggressive mutation.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_DSRS_RUNTIME_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Preset: dsrs_runtime.
- Keep self-improvement actions review-first unless the target is explicitly low-risk.
- Super-loop follow-up text may be generated by an in-process DSRs runtime module before task creation.
- Prefer concise, typed, auditable prompt text that stays close to the default brain workflow instead of inventing new mutation paths.
</system_directive>
"#;

const SELF_IMPROVEMENT_MODE_INSTRUCTION: &str = r#"
<system_directive priority="medium">
SELF-IMPROVEMENT MODE IS ENABLED.
- Prefer capturing durable knowledge when the interaction yields reusable facts, preferences, or stable procedures.
- Use memory promotion, extraction, and dream analysis deliberately instead of duplicating raw notes.
- Keep the working conversation concise and externalize reusable learnings into the brain layer when justified.
</system_directive>
"#;

pub struct PreparedSessionPromptContext {
    pub current_agent_id: String,
    pub session_info: Option<SessionInfo>,
    pub prompt_blocks: Vec<ContentBlock>,
}

pub struct SessionPromptContextDeps {
    pub brain: Arc<BrainService>,
    pub settings_store: Arc<SettingsStore>,
    pub context_prefix: String,
    pub reverse_session_map: Option<Arc<Cache<String, String>>>,
    pub active_session_id: Option<Arc<RwLock<String>>>,
}

fn advisor_instruction_for_preset(preset: &str) -> &'static str {
    match preset.trim() {
        "risk_first" => ADVISOR_MODE_RISK_FIRST_INSTRUCTION,
        "plan_first" => ADVISOR_MODE_PLAN_FIRST_INSTRUCTION,
        _ => ADVISOR_MODE_REVIEW_FIRST_INSTRUCTION,
    }
}

fn self_improvement_instruction_for_preset(preset: &str) -> &'static str {
    match preset.trim() {
        "review_only" => SELF_IMPROVEMENT_MODE_REVIEW_ONLY_INSTRUCTION,
        "safe_apply" => SELF_IMPROVEMENT_MODE_SAFE_APPLY_INSTRUCTION,
        "safe_summarize" => SELF_IMPROVEMENT_MODE_SAFE_SUMMARIZE_INSTRUCTION,
        "dsrs_runtime" => SELF_IMPROVEMENT_MODE_DSRS_RUNTIME_INSTRUCTION,
        "gepa_sidecar" => SELF_IMPROVEMENT_MODE_GEPA_SIDECAR_INSTRUCTION,
        _ => SELF_IMPROVEMENT_MODE_INSTRUCTION,
    }
}

pub fn extract_user_text(prompt: &[ContentBlock]) -> String {
    prompt
        .iter()
        .filter_map(|block| match block {
            ContentBlock::Text(text) if !text.text.starts_with("__MCP_WIDGET_CTX__:") => {
                Some(text.text.clone())
            }
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

pub async fn prepare_session_prompt_context(
    deps: &SessionPromptContextDeps,
    session_id: &str,
    is_subagent: bool,
) -> anyhow::Result<PreparedSessionPromptContext> {
    let settings = deps.settings_store.clone();
    let settings_snapshot = settings.get();
    let current_agent_id = infer_agent_id_from_command(&settings_snapshot.agent.command);

    if let Some(active_session_id) = &deps.active_session_id {
        let db_sid = deps
            .reverse_session_map
            .as_ref()
            .and_then(|reverse_map| reverse_map.get(session_id));
        let effective_sid = db_sid.unwrap_or_else(|| session_id.to_string());
        *active_session_id.write().await = effective_sid;
    }

    let session_info = if is_subagent {
        None
    } else {
        SessionRegistryService::get_session_info(&deps.brain, session_id)?
    };
    let is_new = session_info.is_none();

    if is_new && !is_subagent {
        let ensure_agent_id = if settings.get().agent.team_mode {
            "team".to_string()
        } else {
            current_agent_id.clone()
        };
        info!("New session detected via PromptRequest: {}", session_id);
        let _ = SessionRegistryService::ensure_session(
            &deps.brain,
            session_id,
            &ensure_agent_id,
            &ensure_agent_id,
            "/",
        );
    }

    let should_inject_context = !is_subagent
        && (is_new
            || session_info
                .as_ref()
                .is_some_and(|info| info.message_count == 0));

    let mut prompt_blocks = Vec::new();
    if settings_snapshot.agent.advisor_mode {
        prompt_blocks.push(ContentBlock::Text(TextContent::new(
            advisor_instruction_for_preset(&settings_snapshot.agent.advisor_preset).to_string(),
        )));
    }
    if settings_snapshot.agent.self_improvement_enabled {
        prompt_blocks.push(ContentBlock::Text(TextContent::new(
            self_improvement_instruction_for_preset(
                &settings_snapshot.agent.self_improvement_preset,
            )
            .to_string(),
        )));
    }
    if should_inject_context {
        info!("Injecting context for session: {}", session_id);

        let locale_val = settings.get_value("ui.locale");
        let locale_str = locale_val.as_str().unwrap_or("");
        if !locale_str.is_empty() {
            let lang_name = match locale_str {
                "ko" => "Korean (한국어)",
                "en" => "English",
                "ja" => "Japanese (日本語)",
                "zh" => "Chinese (中文)",
                _ => locale_str,
            };
            let locale_instruction = format!(
                "\n<system_directive priority=\"high\">\n\
                 RESPONSE LANGUAGE: You MUST respond in {}.\n\
                 All artifacts (task, plan, walkthrough) MUST also be written in {}.\n\
                 Use the user's preferred language consistently throughout all outputs.\n\
                 </system_directive>\n",
                lang_name, lang_name
            );
            prompt_blocks.push(ContentBlock::Text(TextContent::new(locale_instruction)));
        }

        let vault_dir = deps.brain.vault_dir();
        let session_artifact_dir = vault_dir.join("sessions").join(session_id);
        let _ = std::fs::create_dir_all(&session_artifact_dir);
        prompt_blocks.push(ContentBlock::Text(TextContent::new(
            ARTIFACT_INSTRUCTION.to_string(),
        )));
        prompt_blocks.push(ContentBlock::Text(TextContent::new(
            deps.context_prefix.clone(),
        )));
    }

    Ok(PreparedSessionPromptContext {
        current_agent_id,
        session_info,
        prompt_blocks,
    })
}
